GET http://localhost:8082/v1/api/hello
Accept: application/json

###
POST http://localhost:8082/v1/api/authenticate
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "admin",
  "password": "1111"
}

### eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNjE0NDg4MzQ0fQ.ixtCR8pv4JDD-nIIvSbrZJfIsLXvacZr-FLqGDPwk1jSuf2nx5Q4ROUBQVSf8HJEjN2zbaIqXooLroaNr36LDw
POST http://localhost:8082/v1/api/accounts
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "test2",
  "password": "1111",
  "email" : "test2@naver.com",
  "age" : "15",
  "userRoles" : ["ROLE_ADMIN"],
  "activated" : "false"
}

###
GET http://localhost:8082/v1/api/accounts/18
Content-Type: application/json
X-Requested-With: XMLHttpRequest
