GET http://localhost:8082/v1/api/hello
Accept: application/json

###
POST http://localhost:8082/v1/api/authenticate
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "admin",
  "password": "1111"
}